obj-y += ipc.o handler.o

obj-$(CONFIG_BAYTRAIL) += byt-ipc.o pmc-ipc.o
obj-$(CONFIG_CHERRYTRAIL)  += byt-ipc.o pmc-ipc.o

obj-$(CONFIG_HASWELL) += hsw-ipc.o
obj-$(CONFIG_BROADWELL) += hsw-ipc.o

obj-$(CONFIG_APOLLOLAKE) += apl-ipc.o

obj-$(CONFIG_CANNONLAKE) += cnl-ipc.o

obj-$(CONFIG_SUECREEK) += sue-ipc.o

obj-$(CONFIG_ICELAKE) += cnl-ipc.o

obj-y += dma-copy.o
