obj-y += dw-dma.o

obj-$(CONFIG_BAYTRAIL) += baytrail/
obj-$(CONFIG_CHERRYTRAIL)  += baytrail/

obj-$(CONFIG_HASWELL) += haswell/
obj-$(CONFIG_BROADWELL) += haswell/

obj-$(CONFIG_APOLLOLAKE) += cavs/
obj-$(CONFIG_CANNONLAKE) += cavs/
obj-$(CONFIG_SUECREEK) += cavs/
obj-$(CONFIG_ICELAKE) += cavs/
