obj-y += \
	eq_iir.o \
	iir.o \
	eq_fir.o \
	fir.o \
	fir_hifi2ep.o \
	fir_hifi3.o \
	tone.o \
	src.o \
	src_generic.o \
	src_hifi2ep.o \
	src_hifi3.o \
	mixer.o \
	mux.o \
	volume.o \
	volume_generic.o \
	volume_hifi3.o \
	switch.o \
	dai.o \
	host.o \
	pipeline.o \
	pipeline_static.o \
	component.o \
	buffer.o
