# SPDX-License-Identifier: GPL-2.0
###
# Forwards building to subdirectories
# ---------------------------------------------------------------------------

# Let clean descend into subdirs
subdir-	+= basic kconfig
