obj-$(CONFIG_BAYTRAIL) += baytrail/
obj-$(CONFIG_CHERRYTRAIL)  += baytrail/

obj-$(CONFIG_HASWELL) += haswell/
obj-$(CONFIG_BROADWELL) += haswell/

obj-$(CONFIG_APOLLOLAKE) += apollolake/
obj-$(CONFIG_CANNONLAKE) += cannonlake/
obj-$(CONFIG_SUECREEK) += suecreek/
obj-$(CONFIG_ICELAKE) += icelake/

obj-$(CONFIG_APOLLOLAKE) += intel/
obj-$(CONFIG_CANNONLAKE) += intel/
obj-$(CONFIG_SUECREEK) += intel/
obj-$(CONFIG_ICELAKE) += intel/
